### ISSUE TITLE
MiddleManager throws up an exception and exits

### ISSUE THREAD

**Issue by loganto** [znly/docker-druid#2]
Hi. Im new to druid and just trying to launch a cluster but something doesnt seem to work right.
Middle manger exits after launch an i cannot run any ingestion tasks.

```
middlemanager_1  | 2016-10-26T21:18:02,626 WARN [main] org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.Server@7308ffff: java.lang.IllegalStateException: Insufficient threads: max=5 < needed(acceptors=1 + selectors=4 + request=1)
middlemanager_1  | java.lang.IllegalStateException: Insufficient threads: max=5 < needed(acceptors=1 + selectors=4 + request=1)
middlemanager_1  | 	at org.eclipse.jetty.server.Server.doStart(Server.java:350) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
middlemanager_1  | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
middlemanager_1  | 	at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:204) [druid-server-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) [java-util-0.27.9.jar:?]
middlemanager_1  | 	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) [druid-api-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:91) [druid-services-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at io.druid.cli.ServerRunnable.run(ServerRunnable.java:40) [druid-services-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at io.druid.cli.Main.main(Main.java:105) [druid-services-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 2016-10-26T21:18:02,635 ERROR [main] io.druid.cli.CliMiddleManager - Error when starting up.  Failing.
middlemanager_1  | java.lang.IllegalStateException: Insufficient threads: max=5 < needed(acceptors=1 + selectors=4 + request=1)
middlemanager_1  | 	at org.eclipse.jetty.server.Server.doStart(Server.java:350) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
middlemanager_1  | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
middlemanager_1  | 	at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:204) ~[druid-server-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) ~[java-util-0.27.9.jar:?]
middlemanager_1  | 	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) ~[druid-api-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:91) [druid-services-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at io.druid.cli.ServerRunnable.run(ServerRunnable.java:40) [druid-services-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at io.druid.cli.Main.main(Main.java:105) [druid-services-0.9.1.1.jar:0.9.1.1]
coordinator_1    | 2016-10-26T21:18:02,633 WARN [main] com.metamx.common.RetryUtils - Failed on try 1, retrying in 968ms.
coordinator_1    | org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: java.sql.BatchUpdateException: Batch entry 0 CREATE TABLE druid_audit 
```

**Comment by loganto** [comment]
druid.server.http.numThreads has to be raised to 6 otherise middleMnager doesn't start.
I've added a PR.
